service: serverless-es2017-sequelize-test

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-central-1

package:
  exclude:
    - "*/*.es6"
    - .*
    - .git/**
    - "*.pdf"
    - "*.md"
    - package.json
    - test/**
    - testdata/**
    - scripts/**
functions:
  users:
    handler: services/users.users
    events:
      - http:
          method: get
          path: users/{userid}
          integration: lambda
          request:
            parameters:
              paths:
                userid: true
          cors: true
